In [1]:
import generators
import numpy as np
import pandas as pd
import json
import systeme as sys
import algo_genetique
import Allocation
from simulation import simulation
generators.set_seed(15)

In [2]:
nb_familles = 5
distribution_process = "poisson"
distribution_setup = "poisson"
process_time_range = (1,7)
setup_time_range = (0,5)
nb_produits_range = (0,100)
dates_arriv_range = (0,100)
families_distribution = "poisson"
arrival_dates_distribution = "poisson"
nb_produits_distribution = "poisson"
vary_nb_produits = True
nb_scenarios = 100
scenarios_path = "all_in_one_generation/scenarios"
fms_path = "all_in_one_generation/fms/instance.json"

In [3]:
#generation de scénarios
scenarios = generators.generate_multiple_scenarios(
    nb_scenarios = nb_scenarios,
    nb_familles = nb_familles,
    nb_produits_range = nb_produits_range,
    dates_arriv_range = dates_arriv_range,
    families_distribution = families_distribution,
    arrival_dates_distribution = arrival_dates_distribution,
    vary_nb_produits = vary_nb_produits,
    nb_produits_distribution = nb_produits_distribution,
    path = scenarios_path
)

#génération d'instance
instance_json = generators.build_instance_json(generators.generate_instance_config(
    nb_familles = nb_familles,
    distribution_process = distribution_process,
    distribution_setup = distribution_setup,
    process_time_range = process_time_range,
    setup_time_range = setup_time_range
), path = fms_path)

#calcul de solution optimale avec algo genetique / recherche tabou

#génération des données singlelabel

#recherche locale pour les symetries

#génération des données multilabel

#entrainement de modèles

#simulation

#comparaison


In [3]:
scenario_path = "scenarios/K0/s1.csv"
scenario = pd.DataFrame(np.nan_to_num(pd.read_csv(scenario_path,header=None, index_col=None, sep=";"), nan=0)).astype(int).iloc[:,:-1]
with open(f'fms/3C7R5F.json', 'r') as json_file:
    dic = json.load(json_file)
system = sys.systeme(dic)

In [12]:
best_solution, best_score, population, evaluations = algo_genetique.algorithme_genetique(
    taille_population=5000,
    system=system,
    scenario=scenario,
    nb_generations=500,
    prcent_best=50,                    
    prcent_fusion=50,
    mutation_rate=0.05,
    max_stagnation=1000,
    verbose=0
)

Initialisation de la population (5000 individus)...

== Génération 1/500 ==
== Génération 2/500 ==
== Génération 3/500 ==
== Génération 4/500 ==
== Génération 5/500 ==
== Génération 6/500 ==
== Génération 7/500 ==
== Génération 8/500 ==
== Génération 9/500 ==
== Génération 10/500 ==
== Génération 11/500 ==
== Génération 12/500 ==
== Génération 13/500 ==
== Génération 14/500 ==
Nouvelle meilleure solution : 658.9020
== Génération 15/500 ==
== Génération 16/500 ==
== Génération 17/500 ==
== Génération 18/500 ==
== Génération 19/500 ==
== Génération 20/500 ==
== Génération 21/500 ==
Nouvelle meilleure solution : 648.5392
== Génération 22/500 ==
== Génération 23/500 ==
== Génération 24/500 ==
== Génération 25/500 ==
== Génération 26/500 ==
== Génération 27/500 ==
== Génération 28/500 ==
== Génération 29/500 ==
== Génération 30/500 ==
== Génération 31/500 ==
== Génération 32/500 ==
== Génération 33/500 ==
== Génération 34/500 ==
== Génération 35/500 ==
== Génération 36/500 ==
== Génération 

In [ ]:
evaluations[:10]

[array([669.53921569, 670.78431373, 670.88235294, ..., 907.02941176,
        909.43137255, 912.39215686]),
 array([669.53921569, 670.60784314, 670.78431373, ..., 770.34313725,
        770.35294118, 770.35294118]),
 array([666.71568627, 669.53921569, 670.60784314, ..., 759.15686275,
        759.16666667, 759.17647059]),
 array([657.71568627, 659.08823529, 661.05882353, ..., 747.44117647,
        747.44117647, 747.45098039]),
 array([652.18627451, 657.71568627, 659.08823529, ..., 741.62745098,
        741.6372549 , 741.64705882]),
 array([652.18627451, 657.71568627, 659.08823529, ..., 738.6372549 ,
        738.6372549 , 738.64705882]),
 array([652.18627451, 657.71568627, 659.08823529, ..., 735.35294118,
        735.35294118, 735.37254902]),
 array([652.18627451, 657.71568627, 659.08823529, ..., 732.98039216,
        732.99019608, 732.99019608]),
 array([652.18627451, 657.71568627, 659.08823529, ..., 731.40196078,
        731.40196078, 731.40196078]),
 array([652.18627451, 657.71568627, 6